### ISSUE TITLE
error: unableToFind(tool: "swift-autolink-extract")

### ISSUE THREAD

**Issue by johnburkey** [finagolfin/swift-android-sdk#109]
Trying to build on macOSX the usual way, what's the standard way around this error?

I see that swift-autolink-extract is in the 5.8 release I downloaded from Swift.org and its a symlink to swift-frontend:
(its here: swift-5.8.1-RELEASE.xctoolchain/usr/bin/swift-autolink-extract)

export TOOLCHAINS=org.swift.5.8.1.20230517101
export AR=/usr/bin/ar      

swift build --destination swiftpm-android-aarch64.json -j 16

**Comment by johnburkey** [comment]
Actually whats the org.swift.5.8.1.20230517101 thing for your build?   I think I just got past the auto link problem, but now I need to find the exact compiler you used so the build system isn't mad.

**Comment by finagolfin** [comment]
I built the 5.8 SDK with Swift 5.8 on linux. In the past, that caused problems on macOS alone for the patch releases, like 5.8.1, so I modified my CI to upload the release SDKs that it tests.

You can simply click the `Actions` tab above and choose a recent CI run, then [download the release SDKs for the architectures you need, like this run](https://github.com/finagolfin/swift-android-sdk/actions/runs/5332141556). That will always be built from the latest patch release and should work for you on macOS.

**Comment by finagolfin** [comment]
Closing since no response, let me know if that CI build worked.
