### ISSUE TITLE
Compile fail when enable cxx-interop

### ISSUE THREAD

**Issue by woxiang04** [finagolfin/swift-android-sdk#118]
hi, finagolfin, when using the [swift android sdk](https://github.com/finagolfin/swift-android-sdk/releases/tag/5.8) add adding the flag -enable-experimental-cxx-interop, compile will fail.

1. command: $SWIFT_PATH/swift build --destination $SWIFT_TOOLCHAIN/android-aarch64.json
2. output:
Building for debugging...
error: link command failed with exit code 1 (use -v to see invocation)
ld.lld: error: unable to find library -lswiftCxx
ld.lld: error: unable to find library -lswiftstd
ld.lld: error: unable to find library -lswiftCxx
ld.lld: error: unable to find library -lswiftstd
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
[7/8] Linking FooModule
3. sample code: https://github.com/woxiang04/FooModule/blob/8b557db14984fc7e01f2f06ab2f09aa54725657d/FooModule.zip

**Comment by woxiang04** [comment]
First thank you for the work to make swift works on Android!
And about the compile failure, do you mean that you just disable the C++ Interop ability because of the significant holes?

**Comment by finagolfin** [comment]
It is still there and partially works, but as those failing or disabled tests show, doesn't always work. That `libswiftCxx.a` library is there in [my native Swift toolchain](https://packages.termux.dev/apt/termux-main/pool/main/s/swift/), but not any `swiftstd` library, not sure what's going on there.

You could take a look at the currently failing C++ Interop tests in that CI log I linked, see what flags it is using, and try to replicate with your own setup, though it is possible that without those two libraries installed in my SDK, it just won't work.

**Comment by woxiang04** [comment]
Wow, the android CI works again, Thanks!

**Comment by finagolfin** [comment]
> will the changes be merged into 5.9?

No, most of those test changes that I amended in my pull were introduced lately in trunk 5.10 anyway, so those problems don't exist in the 5.9 branch.

**Comment by woxiang04** [comment]
OK, got it
