### ISSUE TITLE
How to use windows

### ISSUE THREAD

**Issue by aadog** [finagolfin/swift-android-sdk#148]
How to use windows

**Comment by finagolfin** [comment]
I have not used the Windows toolchain for Swift at all, but it may work with the Android NDK for Windows and my Android SDK for Swift. Try following the directions from the README but on Windows, and let me know if it fails.

**Comment by aadog** [comment]
Thanks for the recovery, how should I use this toolchain, it seems like on windows I don't know how to use

**Comment by finagolfin** [comment]
There are [some instructions online on installing and using it](https://www.swift.org/getting-started/). Are you just trying to build Swift for Windows or are you trying to build Swift for Android on a Windows PC?

**Comment by aadog** [comment]
windows build android so

**Comment by aadog** [comment]
I hope to use windows to cross-compile android so, and it is statically linked

**Comment by finagolfin** [comment]
OK, follow the official instructions to set up a Windows toolchain and try building a Swift package for Windows. Once you have that working, follow the instructions in the README here to cross-compile for Android using that Windows toolchain, and let me know if that works.

**Comment by aadog** [comment]
Yes, the windows tool chain has been installed and windows programs can be compiled correctly. ndk has also been installed.

**Comment by aadog** [comment]
But how do I specify swift to use the android sdk?

**Comment by aadog** [comment]
swift build --build-tests
--destination ~/swift-android-sdk/android-aarch64.json
-Xlinker -rpath -Xlinker \$ORIGIN/swift-5.10-android-24-sdk/usr/lib/aarch64-linux-android

**Comment by aadog** [comment]
Should I use --destination to specify the sdk path?

**Comment by finagolfin** [comment]
Yes, modify that JSON file to have your Windows paths to your Android NDK, SDK, and Swift toolchain, then use the `--destination` flag to cross-compile with `swift build`. Add the `-v` flag to see the compilation commands it produces and correct any mistakes you see.

If it doesn't work and you're not sure how to fix it, paste the failing command here.

**Comment by finagolfin** [comment]
Closing for lack of response, let us know if you got it working.

**Comment by aadog** [comment]
Sorry, he didn't succeed and there seemed to be a lot of bugs
