### ISSUE TITLE
Sporadic CI error when building Swift Argument Parser: error: 'semaphore.h' file not found

### ISSUE THREAD

**Issue by marcprux** [finagolfin/swift-android-sdk#169]
The following error (from this [CI run](https://github.com/finagolfin/swift-android-sdk/actions/runs/10793023322/job/29987994153?pr=167)) sometimes occurs during the "Build Swift Argument Parser package" for the "build-sdk-and-tests" job:

```
Run cd swift-argument-parser
[1/1] Compiling plugin GenerateManual
Building for debugging...
[1/43] Write sources
[1/43] Copying CountLinesTest.txt
[1/43] Write sources
[14/43] Write swift-version--5B7CFD222935D6C9.txt
warning: no such SDK: /usr/local/lib/android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot
[16/45] Emitting module ArgumentParserToolInfo
<unknown>:0: warning: libc not found for 'x86_64-unknown-linux-android24'; C stdlib may be unavailable
[17/45] Compiling ArgumentParserToolInfo ToolInfo.swift
<unknown>:0: warning: libc not found for 'x86_64-unknown-linux-android24'; C stdlib may be unavailable
warning: no such SDK: /usr/local/lib/android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot
[18/46] Wrapping AST for ArgumentParserToolInfo for debugging
error: emit-module command failed with exit code 1 (use -v to see invocation)
[20/79] Emitting module ArgumentParser
<unknown>:0: warning: libc not found for 'x86_64-unknown-linux-android24'; C stdlib may be unavailable
<module-includes>:1:10: note: in file included from <module-includes>:1:
1 | #include "LibcOverlayShims.h"
  |          `- note: in file included from <module-includes>:1:
2 | 

<unknown>:0: error: could not build C module 'SwiftOverlayShims'
/home/runner/work/swift-android-sdk/swift-android-sdk/sdk-config/swift-trunk-android-x86_64-2024-07-15-24-sdk/usr/lib/swift/shims/LibcOverlayShims.h:31:10: error: 'semaphore.h' file not found
 29 | typedef int mode_t;
 30 | #else
 31 | #include <semaphore.h>
    |          `- error: 'semaphore.h' file not found
 32 | #include <sys/ioctl.h>
 33 | #include <sys/types.h>
```

See also [this CI run](https://github.com/marcprux/swift-android-sdk/actions/runs/10808540043/attempts/1), where the first run fails for both trunk and devel on each of aarch64 and armv7. Manually re-running the failed jobs a [second time](https://github.com/marcprux/swift-android-sdk/actions/runs/10808540043/attempts/2) then succeeded. This indicates that there may be some indeterminism taking place. But the fact that it always seems to occur for the Swift Argument Parser stage – which is the first package to be built after the cached toolchain has been fetched and setup – suggests that it may be due to a corrupt cache being downloaded (maybe an in-flight conflict when one cache is being uploaded at the same time as another one being downloaded?)

Perhaps adding some "Validate cached SDK" step could be added to provide further diagnostics, such as running `tree` on the unpacked SDK to report on the contents of the SDK and ensure that 'semaphore.h' is actually there.

**Comment by finagolfin** [comment]
Based on the message `warning: no such SDK: /usr/local/lib/android/sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot`, I think they may be seeding a few Ubuntu images with the new NDK 27b, actions/runner-images#10574. Nothing we can do about such random testing on their end, as I don't want to put in special logic for such rare occurrences, so we'll just rerun when that happens.

**Comment by marcprux** [comment]
Good catch! Glad I didn't spend a lot of effort trying to diagnose it further…
