### ISSUE TITLE
Logging overlay

### ISSUE THREAD

**Issue by lhoward** [finagolfin/swift-android-sdk#192]
Simple feature request: would love to have a logging function that wraps `__android_log_print()` and is exposed to Swift (recalling `__android_log_print()` is not available because it has variadic arguments).

**Comment by marcprux** [comment]
Take a look at https://github.com/skiptools/swift-android-native. PRs welcome!

**Comment by lhoward** [comment]
Well, that looks handy. Guess I'll close this :)

**Comment by lhoward** [comment]
@marcprux maybe you want to subsume [AndroidLooper](https://github.com/PADL/AndroidLooper) into this once I have it debugged?

**Comment by marcprux** [comment]
> @marcprux maybe you want to subsume [AndroidLooper](https://github.com/PADL/AndroidLooper) into this once I have it debugged?

Yes, that would be a great addition!

**Comment by lhoward** [comment]
Great, give me a week or two to iron out bugs. There are a lot of hairy interactions with JNI environments which I'm sure you're aware of!
