### ISSUE TITLE
Error with swift-android-foundation-except-trunk.patch against 6.0.2 release

### ISSUE THREAD

**Issue by marcprux** [finagolfin/swift-android-sdk#197]
The `swift-android-foundation-except-trunk.patch` updated at https://github.com/finagolfin/swift-android-sdk/commit/456b23945fdb839b4394c69d83e3c9211898716e doesn't apply to the (6.0.2) release branch, with the error (seen [here](https://github.com/marcprux/swift-android-sdk/actions/runs/11859143451/job/33051503053#step:9:366)):

```
+ git apply swift-android-ci-except-trunk.patch swift-android-foundation-except-trunk.patch
error: patch failed: swift-foundation/Sources/FoundationEssentials/Platform.swift:142
error: swift-foundation/Sources/FoundationEssentials/Platform.swift: patch does not apply
```

I'm guessing that the release SDK wasn't rebuilt because it was already cached after this fix was applied, and so this failure didn't show up in the CI.

**Comment by finagolfin** [comment]
Yeah, I needed that patch for the 6.0 branch and knew I would need it for the upcoming 6.0.3 also, so I went ahead and applied it to this `except-trunk` patch early, knowing the 6.0.2 SDK was already cached on this CI and unlikely to require a rebuild.

I suggest that you spin that patch off separately in your local pull and only apply it to the devel branch in your CI script, if you need to rebuild all the latest SDKs for some reason.

I know it's a shortcut on this CI, hopefully I can get more of these patches upstreamed before winter break and not have this issue for long.
